[http]
host = '127.0.0.1'
port = 8080
debug = true

[smtp]
host = 'smtp.wherever.org'
port = 465
email = '...'
password = '...'

[mailgun]
api_key = '...'

[sites.testblog]
before_run = 'echo "before post is added"'
after_run = 'echo "after post is added"'
directory = '/path/to/directory'
post_base_path = '_posts/'
asset_base_path = 'assets/'
asset_base_url = '/assets/'
inbox_address = '...'
secret = '...'
approved_senders = []
post_template = '''---
layout: post
title: {title}
---
{content}'''
